const loginFields=[
    {
        labelText:"Phone",
        labelFor:"phone",
        id:"phone",
        name:"phone",
        type:"phone",
        autoComplete:"phone",
        isRequired:true,
        placeholder:"Phone"   
    },
    {
        labelText:"Password",
        labelFor:"password",
        id:"password",
        name:"password",
        type:"password",
        autoComplete:"current-password",
        isRequired:true,
        placeholder:"Password"   
    },
    {
        labelText:"Role",
        labelFor:"role",
        id:"role",
        name:"role",
        type:"text",
        autoComplete:"role",
        isRequired:true,
        placeholder:"Role"   
    }
]

const signupFields=[
    {
        labelText:"Username",
        labelFor:"username",
        id:"username",
        name:"username",
        type:"text",
        autoComplete:"username",
        isRequired:true,
        placeholder:"Username"   
    },
    {
        labelText:"Phone",
        labelFor:"phone",
        id:"phone",
        name:"phone",
        type:"phone",
        autoComplete:"phone",
        isRequired:true,
        placeholder:"Phone"   
    },
    {
        labelText:"Password",
        labelFor:"password",
        id:"password",
        name:"password",
        type:"password",
        autoComplete:"current-password",
        isRequired:true,
        placeholder:"Password"   
    },
    {
        labelText:"Role",
        labelFor:"role",
        id:"role",
        name:"role",
        type:"text",
        autoComplete:"role",
        isRequired:true,
        placeholder:"Role"   
    }
]

export {loginFields,signupFields}